# Generated by Django 5.0 on 2024-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schüler', '0003_test_aufgaben'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='aufgaben',
            field=models.JSONField(default=dict),
        ),
    ]
