# Generated by Django 4.2.4 on 2023-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='jahrgang',
            field=models.IntegerField(default=12, max_length=2),
            preserve_default=False,
        ),
    ]
